# Generated by Django 3.1.5 on 2021-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210703_0954'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='courses',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
