# Generated by Django 3.1.5 on 2021-06-26 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.ManyToManyField(blank=True, to='courses.Comment'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_sections',
            field=models.ManyToManyField(blank=True, to='courses.CourseSection'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.ManyToManyField(blank=True, to='courses.Rate'),
        ),
        migrations.AddField(
            model_name='course',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.sector'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
