# Generated by Django 3.1.5 on 2021-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210626_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_engaged_rating',
            new_name='student_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sector',
        ),
        migrations.AddField(
            model_name='sector',
            name='related_courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
