# Generated by Django 3.1.5 on 2021-06-27 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210626_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
