# Generated by Django 3.1.5 on 2021-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210627_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.ImageField(default='', upload_to='course_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_image',
            field=models.ImageField(default='', upload_to='sector_images'),
            preserve_default=False,
        ),
    ]
