# Generated by Django 3.1.5 on 2021-07-09 09:05

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210708_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to='courses', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='sector_images'),
        ),
    ]
