# Generated by Django 3.1.5 on 2021-07-11 13:01

import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210709_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.ImageField(upload_to='courses', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
