# Generated by Django 3.1.5 on 2021-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210711_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.ImageField(upload_to='courses'),
        ),
    ]
