# Generated by Django 3.1.5 on 2021-07-11 13:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210711_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
