# Generated by Django 3.1.5 on 2021-07-11 19:18

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210711_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='courses', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
