# Generated by Django 3.1.5 on 2021-07-11 22:18

import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210711_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to='courses', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
