# Generated by Django 3.1.5 on 2021-07-12 01:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210711_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
