# Generated by Django 3.1.5 on 2021-07-12 01:30

import cloudinary.models
import cloudinary_storage.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20210712_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
