# Generated by Django 3.1.5 on 2021-07-12 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210712_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
